RESERVED_WORDS_LIST = [
    "TextWindow",
    "ElseIf",
    "EndIf",
    "EndWhile",
    "EndFor",
    "EndSub",
    "Goto",
    "If",
    "Then",
    "Else",
    "While",
    "For",
    "Sub",
    "And",
    "Or",
    "Array",
    "To",
    "Step",
    "Stack",
    "Program",
]

SYMBOLS_DICT = {
    "=": "tkn_equals",
    ".": "tkn_period",
    ",": "tkn_comma",
    ":": "tkn_colon",
    "[": "tkn_left_brac",
    "]": "tkn_right_brac",
    "(": "tkn_left_paren",
    ")": "tkn_right_paren",
    "+": "tkn_plus",
    "-": "tkn_minus",
    "*": "tkn_times",
    "/": "tkn_div",
    "<": "tkn_less",
    ">": "tkn_greater",
}

GRAMMAR = {
    "P": [["eps"], ["SU", "P"], ["S", "P"]],
    "S": [["C"], ["L"], ["BF"], ["ID"], ["GT"]],
    "ID": [["id", "ID1"]],
    "ID1": [["eps"], ["VA"], [":"], ["(", ")"], ["A"]],
    "VA": [["VA_OP_DIM", "=", "EX"]],
    "VA_OP_DIM": [["eps"], ["[", "EX", "]", "VA_OP_DIM"]],
    "C": [["If", "(", "EX", ")", "Then", "CSL", "C1"]],
    "C1": [
        ["EndIf"],
        ["ElseIf", "(", "EX", ")", "Then", "CSL", "C1"],
        ["Else", "CSL", "EndIf"],
    ],
    "CSL": [["eps"], ["S", "CSL"]],
    "L": [["F"], ["W"]],
    "F": [["For", "id", "VA", "To", "EX", "ST", "FSL", "EndFor"]],
    "ST": [["eps"], ["Step", "ST1"]],
    "ST1": [["-", "ES"], ["ES"]],
    "FSL": [["eps"], ["S", "FSL"]],
    "W": [["While", "(", "EX", ")", "WSL", "EndWhile"]],
    "WSL": [["eps"], ["S", "WSL"]],
    "GT": [["Goto", "id"]],
    "SU": [["Sub", "id", "SUSL", "EndSub"]],
    "SUSL": [["eps"], ["S", "SUSL"]],
    "A": [["DIL", "=", "EX"]],
    "DIL": [["[", "EX", "]", "A_OP_DIM"]],
    "A_OP_DIM": [["eps"], ["[", "EX", "]", "A_OP_DIM"]],
    "BF": [["RW", ".", "id", "(", "PAM", ")"]],
    "PAM": [["eps"], ["PAL"]],
    "PAL": [["PA", "PAL1"]],
    "PAL1": [["eps"], [",", "PA", "PAL1"]],
    "PA": [["EX"], ["eps"]],
    "RW": [["TextWindow"], ["Stack"], ["Array"], ["Program"]],
    "EX": [
        ["-", "EB", "EX1"],
        ["EB", "EX1"],
    ],
    "EX1": [["Or", "EB", "EX1"], ["eps"]],
    "EB": [["ER", "EB1"]],
    "EB1": [["And", "ER", "EB1"], ["eps"]],
    "ER": [["ES", "ER1"]],
    "ER1": [["RO", "ES"], ["eps"]],
    "ES": [["EM", "ES1"]],
    "ES1": [["SO", "EM", "ES1"], ["eps"]],
    "EM": [["D", "EM1"]],
    "EM1": [["MO", "D", "EM1"], ["eps"]],
    "SO": [["+"], ["-"]],
    "MO": [["*"], ["/"]],
    "RO": [["<"], [">"], ["="], ["<="], [">="], ["<>"]],
    "D": [
        ["str"],
        ["True"],
        ["False"],
        ["num"],
        ["id", "ID_OP_DIM"],
        ["(", "EX", ")"],
        ["BF"],
    ],
    "ID_OP_DIM": [["eps"], ["[", "EX", "]", "ID_OP_DIM"]],
}
